# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:56:23+00:00

from __future__ import annotations

from enum import Enum
from typing import Dict, List, Optional

from pydantic import BaseModel, Field, RootModel


class ControllersAdvisoriesSystemsResponse(BaseModel):
    data: Optional[Dict[str, List[str]]] = None


class ControllersAdvisoryDetailAttributes(BaseModel):
    cves: Optional[List[str]] = None
    description: Optional[str] = None
    fixes: Optional[str] = None
    modified_date: Optional[str] = None
    packages: Optional[Dict[str, str]] = None
    public_date: Optional[str] = None
    references: Optional[List[str]] = None
    severity: Optional[int] = None
    solution: Optional[str] = None
    synopsis: Optional[str] = None
    topic: Optional[str] = None


class ControllersAdvisoryDetailItem(BaseModel):
    attributes: Optional[ControllersAdvisoryDetailAttributes] = None
    id: Optional[str] = None
    type: Optional[str] = None


class ControllersAdvisoryDetailResponse(BaseModel):
    data: Optional[ControllersAdvisoryDetailItem] = None


class ControllersAdvisoryInlineItem(BaseModel):
    advisory_type: Optional[int] = None
    applicable_systems: Optional[int] = None
    cve_count: Optional[int] = None
    description: Optional[str] = None
    id: Optional[str] = None
    public_date: Optional[str] = None
    severity: Optional[int] = None
    synopsis: Optional[str] = None


class ControllersAdvisoryItemAttributes(BaseModel):
    advisory_type: Optional[int] = None
    applicable_systems: Optional[int] = None
    cve_count: Optional[int] = None
    description: Optional[str] = None
    public_date: Optional[str] = None
    severity: Optional[int] = None
    synopsis: Optional[str] = None


class ControllersFilterData(BaseModel):
    op: Optional[str] = None
    values: Optional[List[str]] = None


class ControllersLinks(BaseModel):
    first: Optional[str] = None
    last: Optional[str] = None
    next: Optional[str] = None
    previous: Optional[str] = None


class ControllersListMeta(BaseModel):
    filter: Optional[Dict[str, ControllersFilterData]] = None
    limit: Optional[int] = None
    offset: Optional[int] = None
    search: Optional[str] = None
    sort: Optional[List[str]] = None
    subtotals: Optional[Dict[str, int]] = None
    total_items: Optional[int] = None


class ControllersPackageDetailAttributes(BaseModel):
    advisory_id: Optional[str] = None
    description: Optional[str] = None
    name: Optional[str] = None
    summary: Optional[str] = None
    version: Optional[str] = None


class ControllersPackageDetailItem(BaseModel):
    attributes: Optional[ControllersPackageDetailAttributes] = None
    id: Optional[str] = None
    type: Optional[str] = None


class ControllersPackageDetailResponse(BaseModel):
    data: Optional[ControllersPackageDetailItem] = None


class ControllersPackageItem(BaseModel):
    name: Optional[str] = None
    summary: Optional[str] = None
    systems_installed: Optional[int] = None
    systems_updatable: Optional[int] = None


class ControllersPackageSystemItem(BaseModel):
    available_evra: Optional[str] = None
    display_name: Optional[str] = None
    id: Optional[str] = None
    installed_evra: Optional[str] = None
    updatable: Optional[bool] = None


class ControllersPackageSystemsResponse(BaseModel):
    data: Optional[List[ControllersPackageSystemItem]] = None
    links: Optional[ControllersLinks] = None
    meta: Optional[ControllersListMeta] = None


class ControllersPackageVersionItem(BaseModel):
    evra: Optional[str] = None


class ControllersPackageVersionsResponse(BaseModel):
    data: Optional[List[ControllersPackageVersionItem]] = None
    links: Optional[ControllersLinks] = None
    meta: Optional[ControllersListMeta] = None


class ControllersPackagesResponse(BaseModel):
    data: Optional[List[ControllersPackageItem]] = None
    links: Optional[ControllersLinks] = None
    meta: Optional[ControllersListMeta] = None


class ControllersSystemAdvisoriesDBLookup(BaseModel):
    advisory_type: Optional[int] = None
    cve_count: Optional[int] = None
    description: Optional[str] = None
    id: Optional[str] = None
    public_date: Optional[str] = None
    severity: Optional[int] = None
    synopsis: Optional[str] = None


class ControllersSystemAdvisoryItemAttributes(BaseModel):
    advisory_type: Optional[int] = None
    cve_count: Optional[int] = None
    description: Optional[str] = None
    public_date: Optional[str] = None
    severity: Optional[int] = None
    synopsis: Optional[str] = None


class ControllersSystemInlineItem(BaseModel):
    created: Optional[str] = None
    culled_timestamp: Optional[str] = None
    display_name: Optional[str] = None
    id: Optional[str] = None
    insights_id: Optional[str] = None
    last_evaluation: Optional[str] = None
    last_upload: Optional[str] = None
    os_major: Optional[str] = None
    os_minor: Optional[str] = None
    os_name: Optional[str] = None
    other_count: Optional[int] = None
    packages_installed: Optional[int] = None
    packages_updatable: Optional[int] = None
    rhba_count: Optional[int] = None
    rhea_count: Optional[int] = None
    rhsa_count: Optional[int] = None
    rhsm: Optional[str] = None
    stale: Optional[bool] = None
    stale_timestamp: Optional[str] = None
    stale_warning_timestamp: Optional[str] = None
    third_party: Optional[bool] = None


class ControllersSystemItemAttributes(BaseModel):
    created: Optional[str] = None
    culled_timestamp: Optional[str] = None
    display_name: Optional[str] = None
    insights_id: Optional[str] = None
    last_evaluation: Optional[str] = None
    last_upload: Optional[str] = None
    os_major: Optional[str] = None
    os_minor: Optional[str] = None
    os_name: Optional[str] = None
    other_count: Optional[int] = None
    packages_installed: Optional[int] = None
    packages_updatable: Optional[int] = None
    rhba_count: Optional[int] = None
    rhea_count: Optional[int] = None
    rhsa_count: Optional[int] = None
    rhsm: Optional[str] = None
    stale: Optional[bool] = None
    stale_timestamp: Optional[str] = None
    stale_warning_timestamp: Optional[str] = None
    third_party: Optional[bool] = None


class ControllersSystemPackageInline(BaseModel):
    description: Optional[str] = None
    evra: Optional[str] = None
    latest_evra: Optional[str] = None
    name: Optional[str] = None
    summary: Optional[str] = None
    updatable: Optional[bool] = None


class ControllersSystemsAdvisoriesRequest(BaseModel):
    advisories: Optional[List[str]] = None
    systems: Optional[List[str]] = None


class ControllersSystemsAdvisoriesResponse(BaseModel):
    data: Optional[Dict[str, List[str]]] = None


class ModelsPackageUpdate(BaseModel):
    advisory: Optional[str] = None
    evra: Optional[str] = None


class Sort(Enum):
    id = 'id'
    name = 'name'
    advisory_type = 'advisory_type'
    synopsis = 'synopsis'
    public_date = 'public_date'
    applicable_systems = 'applicable_systems'


class Tags(RootModel[List[str]]):
    root: List[str]


class FilterSystemProfileSapSidsIn(RootModel[List[str]]):
    root: List[str]


class Sort2(Enum):
    id = 'id'
    display_name = 'display_name'
    last_evaluation = 'last_evaluation'
    last_upload = 'last_upload'
    rhsa_count = 'rhsa_count'
    rhba_count = 'rhba_count'
    rhea_count = 'rhea_count'
    other_count = 'other_count'
    stale = 'stale'


class ApiPatchV1ExportAdvisoriesGetResponse(
    RootModel[List[ControllersAdvisoryInlineItem]]
):
    root: List[ControllersAdvisoryInlineItem]


class ApiPatchV1ExportAdvisoriesAdvisoryIdSystemsGetResponse(
    RootModel[List[ControllersSystemInlineItem]]
):
    root: List[ControllersSystemInlineItem]


class Sort4(Enum):
    id = 'id'
    name = 'name'
    systems_installed = 'systems_installed'
    systems_updatable = 'systems_updatable'


class ApiPatchV1ExportPackagesGetResponse(RootModel[List[ControllersPackageItem]]):
    root: List[ControllersPackageItem]


class ApiPatchV1ExportPackagesPackageNameSystemsGetResponse(
    RootModel[List[ControllersPackageSystemItem]]
):
    root: List[ControllersPackageSystemItem]


class ApiPatchV1ExportSystemsGetResponse(RootModel[List[ControllersSystemInlineItem]]):
    root: List[ControllersSystemInlineItem]


class ApiPatchV1ExportSystemsInventoryIdAdvisoriesGetResponse(
    RootModel[List[ControllersSystemAdvisoriesDBLookup]]
):
    root: List[ControllersSystemAdvisoriesDBLookup]


class ApiPatchV1ExportSystemsInventoryIdPackagesGetResponse(
    RootModel[List[ControllersSystemPackageInline]]
):
    root: List[ControllersSystemPackageInline]


class Sort8(Enum):
    id = 'id'
    display_name = 'display_name'
    last_evaluation = 'last_evaluation'
    last_upload = 'last_upload'
    rhsa_count = 'rhsa_count'
    rhba_count = 'rhba_count'
    rhea_count = 'rhea_count'
    other_count = 'other_count'
    stale = 'stale'
    packages_installed = 'packages_installed'
    packages_updatable = 'packages_updatable'


class Sort10(Enum):
    id = 'id'
    name = 'name'
    type = 'type'
    synopsis = 'synopsis'
    public_date = 'public_date'


class ControllersAdvisoryItem(BaseModel):
    attributes: Optional[ControllersAdvisoryItemAttributes] = None
    id: Optional[str] = None
    type: Optional[str] = None


class ControllersSystemAdvisoryItem(BaseModel):
    attributes: Optional[ControllersSystemAdvisoryItemAttributes] = None
    id: Optional[str] = None
    type: Optional[str] = None


class ControllersSystemItem(BaseModel):
    attributes: Optional[ControllersSystemItemAttributes] = None
    id: Optional[str] = None
    type: Optional[str] = None


class ControllersSystemPackageData(BaseModel):
    description: Optional[str] = None
    evra: Optional[str] = None
    name: Optional[str] = None
    summary: Optional[str] = None
    updatable: Optional[bool] = None
    updates: Optional[List[ModelsPackageUpdate]] = None


class ControllersSystemPackageResponse(BaseModel):
    data: Optional[List[ControllersSystemPackageData]] = None
    links: Optional[ControllersLinks] = None
    meta: Optional[ControllersListMeta] = None


class ControllersSystemsResponse(BaseModel):
    data: Optional[List[ControllersSystemItem]] = None
    links: Optional[ControllersLinks] = None
    meta: Optional[ControllersListMeta] = None


class ControllersAdvisoriesResponse(BaseModel):
    data: Optional[List[ControllersAdvisoryItem]] = None
    links: Optional[ControllersLinks] = None
    meta: Optional[ControllersListMeta] = None


class ControllersAdvisorySystemsResponse(BaseModel):
    data: Optional[List[ControllersSystemItem]] = None
    links: Optional[ControllersLinks] = None
    meta: Optional[ControllersListMeta] = None


class ControllersSystemAdvisoriesResponse(BaseModel):
    data: Optional[List[ControllersSystemAdvisoryItem]] = Field(
        None, description='advisories items'
    )
    links: Optional[ControllersLinks] = None
    meta: Optional[ControllersListMeta] = None


class ControllersSystemDetailResponse(BaseModel):
    data: Optional[ControllersSystemItem] = None
